{
  "_from": "webpack-fail-plugin@^2.0.0",
  "_id": "webpack-fail-plugin@2.0.0",
  "_inBundle": false,
  "_integrity": "sha512-yLeD5BQGtsJM910SXGaos7VbwbY90e/EboyGK1DXaV0+xw08BWDdjALqWcD3UP8yGeAmCBQUnqIE69Y9zwoqcw==",
  "_location": "/webpack-fail-plugin",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "webpack-fail-plugin@^2.0.0",
    "name": "webpack-fail-plugin",
    "escapedName": "webpack-fail-plugin",
    "rawSpec": "^2.0.0",
    "saveSpec": null,
    "fetchSpec": "^2.0.0"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/webpack-fail-plugin/-/webpack-fail-plugin-2.0.0.tgz",
  "_shasum": "638110ed46840b585dab3cd65636c4ccf02a686e",
  "_spec": "webpack-fail-plugin@^2.0.0",
  "_where": "/Users/AF39842/Work/MissionPossible/UI/provmaintform/ent-pmf-war/src/main/capmf",
  "author": {
    "name": "Tiddo Langerak",
    "email": "tiddolangerak@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/TiddoLangerak/webpack-fail-plugin/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Webpack plugin that makes the process return an error code on failure",
  "engines": {
    "node": ">=0.11.12"
  },
  "homepage": "https://github.com/TiddoLangerak/webpack-fail-plugin#readme",
  "keywords": [
    "webpack"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "webpack-fail-plugin",
  "peerDependencies": {
    "webpack": "^1.9.11 || ^2 || ^3"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/TiddoLangerak/webpack-fail-plugin.git"
  },
  "version": "2.0.0"
}
